/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Geometry } from "three-stdlib";
import { useMemo } from "react";
import { useConvexPolyhedron } from "@react-three/cannon";
import { useBox } from '@react-three/cannon';


export default function Desk(props) {
  const { nodes, materials } = useGLTF("/desk.glb");


  return (
    <group {...props} dispose={null}>
      <group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9_Marble_C_150cm_0.geometry}
          material={materials.Marble_C_150cm}
          visible={true}
        >
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/desk.glb");
